# Generated by Django 4.2 on 2023-04-21 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("birth_date", models.DateField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="")),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=255)),
                ("allow_email_contact", models.BooleanField()),
                ("allow_phone_contact", models.BooleanField()),
                ("allow_marketing", models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
