# Generated by Django 4.2 on 2023-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="sku",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
