name: CI/CD

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

permissions:
  contents: write
  issues: read
  checks: write
  pages: write
  id-token: write

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    name : Run Lint Checks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  pytest:
    name : Run Pytest
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"
          cache: true
          cache-dependency-path: "**/pdm.lock"

      - name: Install dependencies
        run: pdm install

      - name: Run tests
        run:  pdm run test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: |
            junit/test-results.xml

      - name: Coverage Report
        uses: 5monkeys/cobertura-action@master
        with:
          report_name: Coverage Report
          path: coverage.xml
          minimum_coverage: 75

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    needs: [pytest]

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"
          cache: true
          cache-dependency-path: "**/pdm.lock"

      - name: Install dependencies
        run: pdm install

      - name: Build Documentation
        working-directory: docs/
        run: "pdm run make html"

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
